app/urls.py
from django.urls import path, include 
from django.conf import settings
from django.conf.urls.static import static
from . import views

app_name = 'app'
urlpatterns = [
    path('accounts/', include('django.contrib.auth.urls')),
    path('register', views.register_user, name="register"),
    path('', views.home, name='home'),
    path('logout/', views.logout_user, name='logout'),
    path('entries', views.entries_list, name='entries'),
    path('entries/<int:entry_id>', views.update_entry_form, name='updateentries'),
    path('entriesform', views.entry_form, name='entriesform'), 
    path('entries_detail/<int:entry_id>', views.entry_detail, name='entriesdetail'),
    path('medicines', views.medicines_list, name='medicines'),
    path('medicine_detail/<int:medicine_id>', views.medicine_detail, name='medicine_detail'),
    path('medicine_update/<int:medicine_id>', views.update_medicine_form, name='medicineupdate'),
    path('medicine_form', views.medicine_form, name="medicine_form"),
    path('archived_medicine', views.archived_medicines_list, name="archived_medicine"),
    path('archived_medicine/<int:medicine_id>', views.archived_medicines_list, name="archived_medicine"), 
    path('charts', views.charts, name='charts'),
    path('api/data/', views.get_data, name='api-data'),

]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

bewellbuddy/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
     path('', include('app.urls'))
]

app/models/entry.py
from django.db import models
from django.contrib.auth.models import User

class Entry(models.Model):

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    entry_date = models.DateField(null=True, blank=True)
    comments = models.CharField(max_length=250, blank=True, null=True)
    

app/models/medicine.py
from django.db import models
from django.contrib.auth.models import User

class Medicine(models.Model):
    
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=50)
    dosage = models.CharField(max_length=50)
    frequency = models.CharField(max_length=50)
    comments = models.CharField(max_length=250)
    start_date = models.DateField(null=True, blank=True)
    end_date = models.DateField(null=True, blank=True)
    uploadImg = models.CharField(max_length=500, null=True, blank=True)

app/models/symptom.py
from django.db import models

class Symptom(models.Model):

    name = models.CharField(max_length=50)
    color = models.CharField(max_length=50)

    def __str__(self):
        return self.name
        

app/models/symptomEntry.py
from django.db import models
from .entry import Entry
from .symptom import Symptom

class SymptomEntry(models.Model):
    entry = models.ForeignKey(Entry, on_delete=models.CASCADE, default=None, related_name="symptoms")
    symptom = models.ForeignKey(Symptom, on_delete=models.CASCADE, default=None)

app/views/charts.py
from django.http import JsonResponse
from django.shortcuts import render
from app.models import Symptom, SymptomEntry, Entry
import datetime

def charts(request):

    return render(request, 'charts.html', {})

def get_data(request, *args, **kwargs):
    today = datetime.date.today()
    todays_date = today - datetime.timedelta(days=30)
    thirty_days_ago = today - datetime.timedelta(days=30)
    entries = Entry.objects.filter(user=request.user).filter(entry_date__gte=thirty_days_ago)
    symptoms = Symptom.objects.all()
    allSymptomEntries = SymptomEntry.objects.all()
    justMySymptomEntries = []


    print('this is the last 30 days', entries)

    for eachSymptomEntry in allSymptomEntries:
        for entry in entries: 
            if eachSymptomEntry.entry_id == entry.id:
                justMySymptomEntries.append(eachSymptomEntry)
                
    total = []
    one = []
    two = []
    three = []
    four = []
    five = []
    six = []
    seven = []
    eight = []
    nine = []
    ten = []

    symptom_names = []
    symptom_colors = []

    for symptom in symptoms:
        symptom_names.append(symptom.name)
        symptom.color = ''.join('#'+ symptom.color)
        symptom_colors.append(symptom.color)

    for symptomEntry in justMySymptomEntries:
            if symptomEntry.symptom_id == 1:
                one.append(symptomEntry)
            if symptomEntry.symptom_id == 2:
                two.append(symptomEntry)
            if symptomEntry.symptom_id == 3:
                three.append(symptomEntry)
            if symptomEntry.symptom_id == 4:
                four.append(symptomEntry)
            if symptomEntry.symptom_id == 5:
                five.append(symptomEntry)
            if symptomEntry.symptom_id == 6:
                six.append(symptomEntry)
            if symptomEntry.symptom_id == 7:
                seven.append(symptomEntry)
            if symptomEntry.symptom_id == 8:
                eight.append(symptomEntry)
            if symptomEntry.symptom_id == 9:
                nine.append(symptomEntry)
            if symptomEntry.symptom_id == 10:
                ten.append(symptomEntry)
            
    thisList = [len(one), len(two), len(three), len(four), len(five), len(six), len(seven), len(eight), len(nine), len(ten)]
    print(thisList)
            
  
    default_items = [1, 4, 3, 5, 2, 6, 7, 9, 3, 2]
    data = {
        "labels": symptom_names, 
        "default": thisList,
        "colors": symptom_colors
    }
    return JsonResponse(data)

app/views/home.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required

@login_required
def home(request):
    if request.method == 'GET':   
            template = 'home.html'
            context = {} 

    return render(request, template, context)

app/templates/Entries/detail.html
{% extends 'shared/base.html' %}

{% block content %}
<div class="container">
    <a href="{% url 'app:entries' %}"><i class="fas fa-arrow-alt-circle-left fa-2x pageFas float-right mr-5"></i></a>
    <div class="d-flex flex-wrap mb-5">
        <h4>{{ entry.entry_date }} </h4>
        <form action="{% url 'app:entriesdetail' entry.id %}" method='POST'>
            {% csrf_token %}
            <input type='hidden' name='delete' value='DELETE'>
            <button class="btn btn-danger ml-5">Delete</button>
        </form>
    </div>
    <div class="pillSection m-5">
        {% for symptomEntry in  entry.symptoms.all %}
            <h3 class="symptomBadge col-1 p-2 badge badge-info badge-pill color-{{ symptomEntry.symptom.color }}" >{{ symptomEntry.symptom }}</h3>
        {% endfor %}            
    </div>
    <div class="m-5">
        {% if entry.comments %}
            <p class="mb-0"><strong>Comments:</strong></p> <p class="ml-3 mb-0 ml-0">{{entry.comments}}</p>
        {% endif %}
    </div>
    <div class="ml-5"> 
     <form action="{% url 'app:updateentries' entry.id %}" method='GET'>
            <button class="btn btn-info">Update</button>
    </form>
    </div>
</div>

{% endblock content %} 

app/templates/Entries/form.html
{% extends 'shared/base.html' %}

{% block content %}
<div class="container">
<a href="{% url 'app:entries' %}"><i class="fas fa-arrow-alt-circle-left fa-2x pageFas float-right mr-5"></i></a>
<h2>Symptoms Entry</h2>
    {% if entry.id is not None %}
    <form action="{% url 'app:entriesdetail' entry.id %}" method="POST" class="entry_form">
    {% else %}
    <form action="{% url 'app:entries' %}" method="POST" class="entry_form">
    {% endif %}
    {% csrf_token %}
        <fieldset>
            {% if entry.id is not None %}
                <label for="entry_date">Enter date:</label>
                <input id="entry_date" type="date" name="entry_date" max="{{ todays_date }}"  value="{{ entry.entry_date|date:'Y-m-d' }}" required>
            {% else %}
                <label for="new_entry_date">Enter date:</label>
                <input id="new_entry_date" type="date" name="new_entry_date" max="{{ todays_date }}" value="{{ todays_date }}" required>
            {% endif %}
        </fieldset>  
        <fieldset>   
        <label class="mt-5"> Symptom Choices: </label>

        <div class="text-center justify-content-center symptomContainer d-flex flex-wrap">
            <ul class="ks-cboxtags p-0">
            {% if entry.id is not None %}
                {% for symptom in symptoms %}
                            <li>
                                <input type="checkbox" id="{{ symptom.id }}" name="symptoms" value={{ symptom.id }}  
                                {% for selected_symptom in selected_symptoms %}{% if selected_symptom.id == symptom.id %} checked {% endif %}{% endfor %}>
                                <label class="color-{{ symptom.color }} mt-4 mb-4" for={{ symptom.id }}>{{ symptom.name }}</label>
                            </li>  
                {% endfor %}
            {% else %}
                {% for symptom in symptoms %}
                    <li>
                        <input type="checkbox" id="{{ symptom.id }}" name="symptoms" value={{ symptom.id }}>
                        <label class="color-{{ symptom.color }} mt-4 mb-4" for={{ symptom.id }}>{{ symptom.name }}</label>
                    </li>
                {% endfor %}
            {% endif %}
        </fieldset>
        </ul>
          <div class="symptomContainer">
            <fieldset>
                <label for="comments">Comments:</label>
                <input class="comments" id="comments" type="text" name="comments" value="{{ entry.comments }}">
            </fieldset>
            {% if entry.id is not None %}
            <div class="text-center">
                <input type="hidden" name="put" value="PUT">
                <input class="btn btn-info" type="submit" value="Update" />
            {% else %}
            <button class="btn btn-info" type="submit">Add Entry</button>
            {% endif %}
            </div
        </div>
    </form>
</div>
{% endblock content %}

app/templates/Entries/list.html
{% extends 'shared/base.html' %}

{% block content %}
<div class="container">
    <a href="{% url 'app:entriesform' %}"><i class="fas fa-plus-circle fa-2x float-right mr-5 pageFas"></i></a>
    <h2>Entries</h2>
    {%for entry in entries %}

      <a href="{% url 'app:entriesdetail' entry.id %}">
        <ul class="list-group list-group-flush entryList ">
            <li class="list-group-item list-group-item-action">
                <div class="d-flex flex-wrap">
                    <div>
                        <h4 class="entryDate mr-4">{{ entry.entry_date }} </h4>
                    </div>
                    <div class="pillSection">
                            {% for symptomEntry in  entry.symptoms.all %}
                                <h3 class="symptomBadge col-1 p-2 badge badge-info badge-pill color-{{ symptomEntry.symptom.color }}" >{{ symptomEntry.symptom }}</h3>
                            {% endfor %}            
                    </div>
                    <div>
                        {% if entry.comments %}
                            <p class="mb-0 comments"><strong>Comments:</strong></p> <p class="ml-3 mb-0 ml-0">{{entry.comments}}</p>
                        {% endif %}
                    </div> 
                </div>
            </li>
        </ul> 
        </a>
    {% endfor %}
</div>

{% endblock content %}

app/templates/home.html
{% extends 'shared/base.html' %}

<script>
{% block jquery %}

var endpoint = '/api/data/'
var defaultData = []
var labels = []
var colors = []
$.ajax({
    method: "GET", 
    url: endpoint,
    success: function(data){
        labels = data.labels
        defaultData = data.default
        colors = data.colors
        setChart()
    }
   
})

function setChart(){
    var ctx = document.getElementById('myChart').getContext('2d');
    var myChart = new Chart(ctx, {
    type: 'doughnut',
    data: {
    labels: labels,
    display: true,
    datasets: [{
            label: '# of Votes',
            data: defaultData,
            backgroundColor: colors,
            }],
        }
    })
       
            scales: {
                yAxes: [{
                    ticks: {
                        beginAtZero: true
                    }
                }]
            }
        }

{% endblock %}
</script>


{% block content %}
 <div class="container">
    <div>
        <h1 class="welcome text-center">Welcome, {{user.first_name}} {{user.last_name}}!</h1>
    </div>
    <div class="d-flex flex-wrap justify-content-between">
            <div class='charts mt-5'>
                <a href="{% url 'app:entries' %}"><h2 class="text-center">Symptoms Overview</h2>
                <p class='text-center'>Previous 30 days</p>
                <p class='text-center'>View Sypmtom Entries</p></a>
                <canvas id="myChart" class="charts"></canvas>
            </div>
        <div class="divWidth">
            <a href="{% url 'app:medicines' %}"><h2 class="text-center mt-5">Current Medicine</h2>
            <p class='text-center'>View Current Medication List</p>
            <img class="homeMed" src="../static/images/drug.png" alt="medication list icon"></a>
        </div>
    </div>
</div> 


{% endblock content %}

app/templates/medicines/archived.html
{% extends 'shared/base.html' %}

{% block content %}
<div class="container">
    <h2>Archived Medication</h2>
    <p>Click one below to view more details</p>
    {%for medicine in medicines %}
    <div clas="d-flex flex-wrap">
        <ul class="list-group list-group-flush entryList">
        <a href="{% url 'app:medicine_detail' medicine.id %}">
        <li class="list-group-item list-group-item-action">
        <div class="d-flex flex-wrap p-1 m-2">
            <h5 class="mr-5">{{ medicine.name }}</h5>
            <p class="ml-5 mr-5">Dosage: {{ medicine.dosage }}</p>
            <p>Frequency: {{ medicine.frequency }}</p>
        </div>
        <div class="d-flex flex-wrap">
            <div class="medicineList_date">
                <p>Start date: {{ medicine.start_date }}</p>
            </div>
            <div class="medicineList_date">
                <p>End date: {{ medicine.end_date }}</p>
            </div>
        </div> 
        </li>
        </a>
        </ul>
    </div>
    {% endfor %}
</div>

{% endblock content %}

app/templates/medicines/detail.html
{% extends 'shared/base.html' %}

{% block content %}
<div>
    <div class="container">
{% if medicine.end_date %}
    <a href="{% url 'app:archived_medicine' %}"><i class="fas fa-arrow-alt-circle-left fa-2x pageFas float-right mr-5"></i></a>
    {% else %}
    <a href="{% url 'app:medicines' %}"><i class="fas fa-arrow-alt-circle-left fa-2x pageFas float-right mr-5"></i></a>
{% endif %}
    <div class="d-flex flex-wrap">
        <h2>{{ medicine.name }}</h2>

        <form action="{% url 'app:medicine_detail' medicine.id %}" method='POST'>
            {% csrf_token %}
            <input type='hidden' name='delete' value='DELETE'>
            <button class="btn btn-danger ml-5">Delete</button>
        </form>
    </div>
    <div class="d-flex flex-wrap">
        <p class="medicineKeys">Dosage:</p> <p>{{ medicine.dosage }}</p>
    </div>
    <div class="d-flex flex-wrap">
        <p class="medicineKeys">Frequency:</p> <p>{{ medicine.frequency }}</p>
    </div>
    <div class="d-flex flex-wrap">
        <p class="medicineKeys">Start date:  <p>{{ medicine.start_date }}</p>
    </div>
        {% if medicine.end_date %}
    <div class="d-flex flex-wrap">
        <p class="medicineKeys">End date:  <p>{{ medicine.end_date }}</p>
    </div> 
        {% endif %}
        {% if medicine.comments %}
    <div class="d-flex flex-wrap">
        <p class="medicineKeys">Comments:  <p>{{ medicine.comments }}</p>
    </div>
        {% endif %}
        {% if medicine.uploadImg %}
    <div class="d-flex flex-wrap">
       <img class="maxphotowidth" src="{{ medicine.uploadImg }}"  alt="{{ medicine.name }}" />
       {% endif %}
    </div>
    <div class="container">
        <form action="{% url 'app:medicineupdate' medicine.id %}" method='GET'>
            <button class="btn btn-info m-2">Update</button>
        </form>
    </div>
    </div>

{% endblock content %} 

app/templates/medicines/form.html
{% extends 'shared/base.html' %}

{% block content %}
<div class="container">
<a href="{% url 'app:medicines' %}"><i class="fas fa-arrow-alt-circle-left fa-2x pageFas float-right mr-5"></i></a>
<h2>Medicine Entry</h2>
    {% if medicine.id is not None %}
    <form action="{% url 'app:medicine_detail' medicine.id %}" method="POST" class="form">
      {% else %}
    <form action="{% url 'app:medicines' %}" method="POST" class="form">
    {% endif %}
    {% csrf_token %}
        <fieldset>
            <label for="name">Name:</label>
            <input class="medname" id="name" type="text" name="name" value="{{ medicine.name }}" required>
        </fieldset>
         <fieldset>
            <label for="dosage">Dosage:</label>
            <input id="dosage" type="text" name="dosage" value="{{ medicine.dosage }}" required>
        </fieldset>
        <fieldset>
            <label for="frequency">Frequency:</label>
            <input id="frequency" type="text" name="frequency" value="{{ medicine.frequency }}" required>
        </fieldset>
        {% if medicine.id is not None %}
        <fieldset>
            <label for="start_date">Start Date:</label>
            <input id="start_date" type="date" name="start_date" value={{ medicine.start_date|date:'Y-m-d'  }} required>
        </fieldset>
        {% else %}
        <fieldset>
            <label for="start_date">Start Date:</label>
            <input id="start_date" type="date" name="start_date" value={{ todays_date }} required>
        </fieldset>
        {% endif %}
        {% if medicine.id is not None %}
         <fieldset>
            <label for="end_date">End Date:</label>
            <input id="end_date" type="date" name="end_date" value={{ medicine.end_date|date:'Y-m-d'  }} >
        </fieldset>
        {% else %}
        <fieldset>
            <label for="end_date">End Date:</label>
            <input id="end_date" type="date" name="end_date">
        </fieldset>
        {% endif %}
         <fieldset>
            <label for="comments">Comments:</label>
            <input class="medfield" id="comments" type="text" name="comments" value="{{ medicine.comments }}" >
        </fieldset>
        <fieldset>
            <label for="uploadImg">Image Url:</label>
            <input class="medfield" id="uploadImg" type="text" name="uploadImg" value={{ medicine.uploadImg }}>
        </fieldset>
        {% if medicine.id is not None %}
            <div class="text-center">
                <input type="hidden" name="put" value="PUT">
                <input class="btn btn-info" type="submit" value="Update" />
            </div>
            {% else %}
            <button class="btn btn-info" type="submit">Add Entry</button>
            {% endif %}
    </form>
</div>
{% endblock content %}

app/templates/medicines/list.html
{% extends 'shared/base.html' %}

{% block content %}
<div class="container">
    <a href="{% url 'app:medicine_form' %}"><i class="fas fa-plus-circle fa-2x float-right mr-5 pageFas"></i></a>
    <h2>Current Medications</h2>
    <p>Click one below to view more details</p>
    {%for medicine in medicines %}
    <ul class="list-group list-group-flush entryList">
    <a href="{% url 'app:medicine_detail' medicine.id %}">
        <div>
            <li class="list-group-item list-group-item-action">
            <div class="d-flex flex-wrap">
                <div class="medicineList_name">
                    <p>{{ medicine.name }}</p>
                </div> 
                <div class="medicineList">
                    <p>{{ medicine.dosage }}</p>
                </div>
                <div class="medicineList">
                    <p>{{ medicine.frequency }}</p>
                </div>
            </div>
            </li>
        </div></a>
        </ul>
        {% endfor %}
</div>

{% endblock content %}

app/templates/shared/base.html
{% load static %}
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <title>Be Well Buddy</title>
    <link rel="icon" 
      type="image/png" 
      href="static/images/BWB.png">   
    <!-- Bootstrap CSS CDN -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css" integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">
    <!-- Our Custom CSS -->
      <link rel="stylesheet" href='../../static/styles/base.css'>

    <!-- Font Awesome JS -->
 <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.14.0/css/all.css" integrity="sha384-HzLeBuhoNPvSl5KYnjx0BT+WB0QEEqLprO+NBkkk5gbc67FTaL7XIGa2w1L0Xbgc" crossorigin="anonymous">

</head>
<body>
    <div class="wrapper">
        <!-- Sidebar  -->
        <nav id="sidebar">
            <div class="sidebar-header text-center d-flex flex-wrap justify-content-center"> 
                <h3 class="menuTitle"><img class="bwbIcon m-0 p-0" src="../../static/images/BWB.png" alt="Be Well Buddy Icon"/>  Be Well Buddy</h3>
                <strong><img class="bwbIconCollapse" src="../../static/images/BWB.png" alt="Be Well Buddy Icon"/></strong>
                <strong>BWB</strong>
            </div>
            <ul class="list-unstyled components">
                <li class="active">
                    <a href="/">
                       <img class="menuIcon" src="../../static/images/home.png" alt="home icon"/> 
                        Home
                    </a>
                </li>
                <li>
                    <a href="#symptomSubmenu" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle">
                        <img class="menuIcon" src="../../static/images/symptomTracker.png" alt="home icon"/> 
                        Symptom Tracker
                    </a>
                    <ul class="collapse list-unstyled" id="symptomSubmenu">
                        <li>
                            <a class="menu-list" href="{% url 'app:entries' %}">View</a>
                        </li>
                        <li>
                            <a class="menu-list" href="{% url 'app:entriesform' %}">Add</a>
                        </li>
                    </ul>
                    <a href="#medSubmenu" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle">
                        <img class="menuIcon" src="../../static/images/medicine.png" alt="medicine icon"/> 
                        Medicine Tracker
                    </a>
                    <ul class="collapse list-unstyled" id="medSubmenu">
                        <li>
                            <a class="menu-list" href="{% url 'app:medicines' %}">View</a>
                        </li>
                        <li>
                            <a class="menu-list" href="{% url 'app:medicine_form' %}">Add</a>
                        </li>
                        <li>
                            <a class="menu-list" href="{% url 'app:archived_medicine' %}">Archived</a>
                        </li>
                    </ul>
                </li>
                <li>
                    
                    {% comment %} Future use for adding Recall functionality
                    <a href="#">
                      <img class="menuIcon" src="../../static/images/recall.png" alt="Recall icon"/> 
                      Medicine Recalls
                    </a> {% endcomment %}
                </li>
                <li class="active">
                    <a href="{% url 'app:logout' %}">
                       <img class="menuIcon" src="../../static/images/logout.png" alt="loutout icon"/> 
                        Logout
                    </a>
                </li>
            </ul>
        </nav>

        <!-- Page Content  -->
        <div id="content">

            <nav class="navbar navbar-expand-lg navbar-light bg-light">
                <div class="container-fluid">
                    <button type="button" id="sidebarCollapse" class="btn btn-info hello">  
                        <i class="fas fa-bars"></i>
                    </button>
                </div>
            </nav>
            <main class="main-content">{% block content %} {% endblock %}</main>
        </div>
    </div>

    <!-- jQuery CDN - Slim version (=without AJAX) -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <!-- Popper.JS -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js" integrity="sha384-cs/chFZiN24E4KMATLdqdvsezGxaGsi4hLGOzlXwp5UZB1LY//20VyM2taTB4QvJ" crossorigin="anonymous"></script>
    <!-- Bootstrap JS -->
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js" integrity="sha384-uefMccjFJAIv6A+rW+L4AHf99KvxDjWSu1z9VI8SKNVmz4sk7buKt/6v9KI65qnm" crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src='https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.5.0/Chart.min.js'></script>
    <script type="text/javascript">
        $(document).ready(function () {
            $('#sidebarCollapse').on('click', function () {
                $('#sidebar').toggleClass('active');
            });
        });
        $(document).ready(function(){
            $(".entry_form").submit(function(){
                if ($('input:checkbox').filter(':checked').length < 1){
                    alert("Please check at least one symptom!");
                return false;
                }
            });
        });
       
    $(document).ready(function(){
      {% block jquery %}{% endblock %}
    })

</script>

</body>

</html>